title: Hacker101
email: support@hackerone.com
description: >-
  Hacker101 is a free class for web security. Whether you're a programmer with an interest in bug bounties or a seasoned security professional, Hacker101 has something to teach you.
author: HackerOne
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Hacker0x01
github_username:  Hacker0x01

# Build settings
plugins:
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:

collections:
  resources:

exclude:
  [
    .bundle,
    CNAME,
    Gemfile,
    Gemfile.lock,
    LICENSE,
    node_modules,
    README.md,
    update_bootstrap.sh,
  ]
